# Generated by Django 5.1.6 on 2025-03-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
    ]
